### ISSUE TITLE
Login outh giving error

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/codingblocks.online#11]
This comes after login from accounts.codingblocks.com
![screen shot 2017-09-23 at 8 21 10 pm](https://user-images.githubusercontent.com/22571395/30774229-e9722dc8-a09c-11e7-822b-367a9fec43a9.png)

**Comment by abhishek97** [comment]
Thanks for bringing that up.
However, this is a deployment issue and not related to this repository.
It'll be fixed soon.

**Comment by 0xnmn** [comment]
Cool. Must then be working locally, haven't checked yet. Thanks.
