### ISSUE TITLE
Not able to open Classroom after Login

### ISSUE THREAD

**Issue by aayusharora** [coding-blocks/codingblocks.online#19]
Error seems to be in Backend.
Please check 
https://bitbucket.org/coding-blocks/amoeba-backend/issues/3/error-for-classroom-route

**Comment by aayusharora** [comment]
@abhishek97 Please check this on priority.

**Comment by abhishek97** [comment]
@aayusharora Post a screenshot of console error?  have you checked on the live app at https://codingblocks.online/classroom? it seems to work for me.

**Comment by aayusharora** [comment]
The screenshot of live Error is posted on https://bitbucket.org/coding-blocks/amoeba-backend/issues/3/error-for-classroom-route
mentioned above already.
There is no error in browser console.

**Comment by aayusharora** [comment]
@abhishek97 The online version seems to work correctly.

**Comment by abhishek97** [comment]
Then it might be due to invalid/NULL data entries in DB. Closing this for now. Please Reopen if this happens again on production.
