### ISSUE TITLE
Disabling Service Workers

### ISSUE THREAD

**Issue by aayusharora** [coding-blocks/codingblocks.online#2]
Service Workers are doing a lot of issues while working and testing the application.
It is better to make a seperate branch **codingblocks.online PWA** and push the PWA version there, removing service workers from this branch.

**Comment by abhishek97** [comment]
I'll do it. 
But we need to decide if we want to do a pwa, cuz if not, there is no point in maintaining two version of the project. 

`SW_DISABLE` env variable can be set to disable Service worker for purpose of development.
