### ISSUE TITLE
Gap after video collumn

### ISSUE THREAD

**Issue by abhishek97** [coding-blocks/codingblocks.online#24]

**Comment by 0xnmn** [comment]
Resolved

**Comment by sd5869** [comment]
This is unresolved 
![image](https://user-images.githubusercontent.com/8257951/31489392-15fcf9e8-af5e-11e7-90a7-1aa547dd3080.png)

**Comment by abhishek97** [comment]
@hereisnaman although the gap column is removed, the controls for youtube are not visible. Please fix this.

**Comment by 0xnmn** [comment]
@sd5869 can you please share the browser window aspect ratio so that I can test an debug. I guess the following will work. Still I would be sure only after testing.  
```
{
  height: calc(100vh - 94px);
  width: 100%;
}
```
