### ISSUE TITLE
remove scrollbars in course section description 

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/codingblocks.online#7]
looking ugly here 

![image](https://user-images.githubusercontent.com/1327050/30745695-d53e1944-9fc4-11e7-8c7b-efcd909d60b1.png)

**Comment by aayusharora** [comment]
@championswimmer I can't reproduce this issue in Safari and Chrome.
Which OS and browser have you used to test this.

**Comment by championswimmer** [comment]
@aayusharora firefox and Edge, all OS
