### ISSUE TITLE
table of contents come at bottom in reponsive layout 

### ISSUE THREAD

**Issue by witty123** [coding-blocks/codingblocks.online#71]
<img width="198" alt="screen shot 2017-12-13 at 2 12 54 pm" src="https://user-images.githubusercontent.com/7976098/33929539-d7be8006-e00f-11e7-9a30-669946610a94.png">
<img width="193" alt="screen shot 2017-12-13 at 2 14 25 pm" src="https://user-images.githubusercontent.com/7976098/33929573-f88d7a08-e00f-11e7-830a-348d4f995ec1.png">
<img width="1440" alt="screen shot 2017-12-13 at 2 20 09 pm" src="https://user-images.githubusercontent.com/7976098/33929807-cd9a3b5a-e010-11e7-9e06-0a0bfb80cd0e.png">

**Comment by witty123** [comment]
@aayusharora this is happening on staging, please fix this asap !!

**Comment by aayusharora** [comment]
Fixed!! @witty123
